### ISSUE TITLE
Update to Lithium 0.7.3+ / MC 1.17+

### ISSUE THREAD

**Issue by Artellia** [2No2Name/lithium-fabric#7] opened 2021-07-19 01:05 UTC
Can you please update to Lithium 0.7.3+ / MC 1.17+ or get this merged in instead?

**Comment by NebelNidas** [comment] 2021-10-08 19:06
Duplicate of https://github.com/2No2Name/hopperOptimizations/issues/33.

**Closed as completed** 2022-12-07 19:48 UTC
Labels: enhancement
